"""update route Cargo model

Revision ID: 0f8a4a66c5c4
Revises: 433598665858
Create Date: 2025-03-26 04:52:54.347262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8a4a66c5c4'
down_revision = '433598665858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        # Set a default value for the 'route' field to avoid NOT NULL constraint errors
        batch_op.add_column(sa.Column('route', sa.String(length=300), nullable=False, server_default='default_route'))
        
        # Drop the 'destination' column
        batch_op.drop_column('destination')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        # Re-add the 'destination' column
        batch_op.add_column(sa.Column('destination', sa.String(length=300), nullable=False))
        
        # Alter the 'route' column to allow NULL values in case of downgrade
        batch_op.alter_column('route',
               existing_type=sa.String(length=300),
               nullable=True)

    # ### end Alembic commands ###
