"""add last_seen to users

Revision ID: 187bf3560e9b
Revises: 9f0d0cf7f36d
Create Date: 2025-04-04 10:31:14.225625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187bf3560e9b'
down_revision = '9f0d0cf7f36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
