"""add cargo image to truck requests

Revision ID: 1c58ad2f0ba3
Revises: 76aeb3b9e097
Create Date: 2025-04-04 08:26:24.853329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c58ad2f0ba3'
down_revision = '76aeb3b9e097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck_request', schema=None) as batch_op:
        batch_op.drop_column('cargo_image')

    # ### end Alembic commands ###
