"""empty message

Revision ID: 36d0127b2977
Revises: 69a79d315e6d
Create Date: 2025-04-01 15:03:02.091532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d0127b2977'
down_revision = '69a79d315e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('destination', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('cargo_details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck_request', schema=None) as batch_op:
        batch_op.drop_column('cargo_details')
        batch_op.drop_column('destination')
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
