"""Add route to Cargo model

Revision ID: 433598665858
Revises: 4f148cde8080
Create Date: 2025-03-26 04:42:38.549060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433598665858'
down_revision = '4f148cde8080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.drop_column('route')

    # ### end Alembic commands ###
