"""Add origin field to Cargo model

Revision ID: 4f148cde8080
Revises: 259ea569b31f
Create Date: 2025-03-25 15:09:52.192264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f148cde8080'
down_revision = '259ea569b31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=300), nullable=False, server_default='Unknown'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
