"""Renamed route to destination in Cargo model

Revision ID: 9e696d2e50fa
Revises: 0f8a4a66c5c4
Create Date: 2025-03-27 17:16:32.526891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e696d2e50fa'
down_revision = '0f8a4a66c5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=300), nullable=False))
        batch_op.drop_column('route')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route', sa.VARCHAR(length=300), server_default=sa.text("'default_route'"), nullable=False))
        batch_op.drop_column('destination')

    # ### end Alembic commands ###
