"""contact driver

Revision ID: 9f0d0cf7f36d
Revises: 1c58ad2f0ba3
Create Date: 2025-04-04 08:53:11.997231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0d0cf7f36d'
down_revision = '1c58ad2f0ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_contact', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_column('driver_contact')

    # ### end Alembic commands ###
