"""status field to truck and cargo models

Revision ID: d1f322cf4582
Revises: 9e696d2e50fa
Create Date: 2025-03-29 04:31:32.936214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f322cf4582'
down_revision = '9e696d2e50fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
